# Generated by Django 4.2.18 on 2025-02-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_panel", "0002_studentanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentanswer",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
