# Generated by Django 4.2.18 on 2025-02-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_panel", "0004_alter_studentanswer_unique_together_studentexam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="key",
        ),
    ]
